// dfeafa
/* fdf
fasa
*/
/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#include "dasda.h"
#include <ffdf>
#include <stdio.h>

int foo(int a, float b);
int _foo(int a, float b);
int foo(int a, float b);
int foo(void);
int foo();

int foo(int a, float b)
{
    printf("Hello, world!");
};

int foo(void)
{
    printf("Hello, world2!");
};

int foo()
{
    printf("Hello, world3!");
};