/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

struct _1_bubblesort_1_opaque_NodeStruct;
struct _IO_FILE;
struct timeval;
extern int gettimeofday(struct timeval *tv, void *tz);
extern int pthread_cond_broadcast(int *cond);
extern int getpagesize();
extern int posix_memalign(void **memptr, unsigned int alignment, unsigned int size);
extern int pthread_join(void *thread, void **value_ptr);
extern unsigned int strlen(char const *s);
extern int open(char const *filename, int oflag, ...);
extern int pthread_barrier_destroy(int *barrier);
extern int pthread_mutex_init(int *mutex, int *attr);
extern int strncmp(char const *s1, char const *s2, unsigned int maxlen);
extern int printf(char const *format, ...);
extern int pthread_cond_signal(int *cond);
extern int pthread_barrier_init(int *barrier, int *attr, unsigned int count);
extern int raise(int sig);
extern int scanf(char const *format, ...);
typedef struct _1_bubblesort_1_opaque_NodeStruct *_1_bubblesort_1_opaque_StructureType;
extern int unlink(char const *filename);
struct _1_bubblesort_1_opaque_NodeStruct
{
    struct _1_bubblesort_1_opaque_NodeStruct *next;
    int data;
    struct _1_bubblesort_1_opaque_NodeStruct *prev;
};
extern int pthread_barrier_wait(int *barrier);
extern double difftime(long tv1, long tv0);
extern int pthread_mutex_lock(int *mutex);
extern void *memcpy(void *s1, void const *s2, unsigned int size);
extern void *dlsym(void *handle, char *symbol);
extern int gethostname(char *name, unsigned int namelen);
extern unsigned long strtoul(char const *str, char const *endptr, int base);
extern void abort();
extern int fprintf(struct _IO_FILE *stream, char const *format, ...);
extern void free(void *ptr);
extern void signal(int sig, void *func);
extern void exit(int status);
void main(void);
void bubblesort(int n, int *a);
typedef struct _IO_FILE FILE;
extern int close(int filedes);
extern int mprotect(void *addr, unsigned int len, int prot);
extern double log(double x);
extern double strtod(char const *str, char const *endptr);
extern double ceil(double x);
struct _1_bubblesort_1_opaque_NodeStruct *_1_bubblesort_1_opaque_list_1 = (struct _1_bubblesort_1_opaque_NodeStruct *)0;
extern int fclose(void *stream);
extern int fcntl(int filedes, int cmd, ...);
extern int pthread_cond_wait(int *cond, int *mutex);
extern void perror(char const *str);
extern int pthread_cond_init(int *cond, int *attr);
extern int write(int filedes, void *buf, unsigned int nbyte);
extern int ptrace(int request, void *pid, void *addr, int data);
extern float strtof(char const *str, char const *endptr);
extern unsigned int strnlen(char const *s, unsigned int maxlen);
struct timeval
{
    long tv_sec;
    long tv_usec;
};
extern long clock(void);
extern void qsort(void *base, unsigned int nel, unsigned int width, int (*compar)(void *a, void *b));
extern long time(long *tloc);
extern int rand();
extern int read(int filedes, void *buf, unsigned int nbyte);
extern int strcmp(char const *a, char const *b);
extern void *fopen(char const *filename, char const *mode);
extern double sqrt(double x);
struct _1_bubblesort_1_opaque_NodeStruct *_1_bubblesort_1_opaque_ptr_1 = (struct _1_bubblesort_1_opaque_NodeStruct *)0;
extern long strtol(char const *str, char const *endptr, int base);
extern int snprintf(char *str, unsigned int size, char const *format, ...);
extern void *malloc(unsigned int size);
extern int nanosleep(int *rqtp, int *rmtp);
extern int pthread_mutex_unlock(int *mutex);
extern int pthread_create(void *thread, void *attr, void *start_routine, void *arg);
extern int atoi(char const *s);
extern int fseek(struct _IO_FILE *stream, long offs, int whence);
extern int fscanf(struct _IO_FILE *stream, char const *format, ...);
struct _1_bubblesort_1_opaque_NodeStruct *_1_bubblesort_1_opaque_list_2 = (struct _1_bubblesort_1_opaque_NodeStruct *)0;
struct _1_bubblesort_1_opaque_NodeStruct *_1_bubblesort_1_opaque_ptr_2 = (struct _1_bubblesort_1_opaque_NodeStruct *)0;
void megaInit(void);
void bubblesort(int n, int *a)
{
    int i;
    int j;
    int k;
    int x;
    struct _1_bubblesort_1_opaque_NodeStruct *p7;
    int r8;
    struct _1_bubblesort_1_opaque_NodeStruct *p9;
    int r10;
    struct _1_bubblesort_1_opaque_NodeStruct *p11;

    {
        { /* __blockattribute__(__ATOMIC__)*/
            p7 = (struct _1_bubblesort_1_opaque_NodeStruct *)malloc(sizeof(struct _1_bubblesort_1_opaque_NodeStruct));
            p7->next = p7;
            p7->prev = p7;
            _1_bubblesort_1_opaque_list_1 = p7;
            r10 = rand();
            p11 = (struct _1_bubblesort_1_opaque_NodeStruct *)malloc(sizeof(struct _1_bubblesort_1_opaque_NodeStruct));
            p11->data = 0 * r10;
            p11->next = _1_bubblesort_1_opaque_list_1->next;
            p11->prev = _1_bubblesort_1_opaque_list_1;
            (_1_bubblesort_1_opaque_list_1->next)->prev = p11;
            _1_bubblesort_1_opaque_list_1->next = p11;
            r8 = rand();
            p9 = (struct _1_bubblesort_1_opaque_NodeStruct *)malloc(sizeof(struct _1_bubblesort_1_opaque_NodeStruct));
            p9->data = 1 * r8;
            p9->next = _1_bubblesort_1_opaque_list_1->next;
            p9->prev = _1_bubblesort_1_opaque_list_1;
            (_1_bubblesort_1_opaque_list_1->next)->prev = p9;
            _1_bubblesort_1_opaque_list_1->next = p9;
            _1_bubblesort_1_opaque_ptr_1 = _1_bubblesort_1_opaque_list_1->next;
            _1_bubblesort_1_opaque_ptr_2 = _1_bubblesort_1_opaque_ptr_1;
        }

        k = n - 1;
        while (k >= 0)
        {
            j = -1;
            i = 1;
            while (i <= k)
            {
                if (_1_bubblesort_1_opaque_ptr_1 != _1_bubblesort_1_opaque_ptr_2)
                {
                    if (_1_bubblesort_1_opaque_ptr_1 != _1_bubblesort_1_opaque_ptr_2)
                    {
                        __asm__ volatile(".byte 0x0,0x44,0x89,0xe0,0xe9,0xfd,0xff,0xff" :);
                    }
                    else
                    {
                        bubblesort(r8, a);
                    }
                }
                else
                {
                }
                if (*(a + (i - 1)) > *(a + i))
                {
                    j = i - 1;
                    x = *(a + j);
                    *(a + j) = *(a + i);
                    *(a + i) = x;
                }
                if (_1_bubblesort_1_opaque_ptr_1 == _1_bubblesort_1_opaque_ptr_2)
                {
                }
                else
                {
                    bubblesort(k, a);
                }
                i++;
            }
            k = j;
        }
        {
            if (_1_bubblesort_1_opaque_ptr_1 == _1_bubblesort_1_opaque_ptr_2)
            {
            }
            else
            {
                bubblesort(i, a);
            }
            return;
        }
    }
}
void megaInit(void)
{

    {
    }
}
void main(void)
{

    {
        megaInit();
    }
}
