/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

struct _2_main_1_opaque_NodeStruct ;
struct _IO_FILE ;
struct timeval ;
extern int gettimeofday(struct timeval *tv , void *tz ) ;
extern int pthread_cond_broadcast(int *cond ) ;
char **_global_argv  =    (char **)0;
extern int getpagesize() ;
extern int posix_memalign(void **memptr , unsigned int alignment , unsigned int size ) ;
struct _2_main_1_opaque_NodeStruct {
   struct _2_main_1_opaque_NodeStruct *next ;
   int data ;
   struct _2_main_1_opaque_NodeStruct *prev ;
};
struct _2_main_1_opaque_NodeStruct *_2_main_1_opaque_list_1  =    (struct _2_main_1_opaque_NodeStruct *)0;
extern int pthread_join(void *thread , void **value_ptr ) ;
extern unsigned int strlen(char const   *s ) ;
extern int open(char const   *filename , int oflag  , ...) ;
typedef struct _2_main_1_opaque_NodeStruct *_2_main_1_opaque_StructureType;
extern int pthread_barrier_destroy(int *barrier ) ;
extern int pthread_mutex_init(int *mutex , int *attr ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned int maxlen ) ;
extern int printf(char const   * __restrict  __format  , ...) ;
int _global_argc  =    0;
extern int pthread_cond_signal(int *cond ) ;
extern int pthread_barrier_init(int *barrier , int *attr , unsigned int count ) ;
extern int raise(int sig ) ;
extern int scanf(char const   *format  , ...) ;
char **_global_envp  =    (char **)0;
extern int unlink(char const   *filename ) ;
extern int pthread_barrier_wait(int *barrier ) ;
extern double difftime(long tv1 , long tv0 ) ;
extern int pthread_mutex_lock(int *mutex ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned int size ) ;
extern void *dlsym(void *handle , char *symbol ) ;
extern int gethostname(char *name , unsigned int namelen ) ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern void abort() ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern void free(void *ptr ) ;
extern void signal(int sig , void *func ) ;
extern void exit(int status ) ;
int main(int argc , char **argv , char **_formal_envp ) ;
typedef struct _IO_FILE FILE;
extern int close(int filedes ) ;
extern int mprotect(void *addr , unsigned int len , int prot ) ;
extern double log(double x ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
struct _2_main_1_opaque_NodeStruct *_2_main_1_opaque_ptr_1  =    (struct _2_main_1_opaque_NodeStruct *)0;
extern double ceil(double x ) ;
extern int fclose(void *stream ) ;
extern int fcntl(int filedes , int cmd  , ...) ;
extern int pthread_cond_wait(int *cond , int *mutex ) ;
extern void perror(char const   *str ) ;
extern int pthread_cond_init(int *cond , int *attr ) ;
extern int write(int filedes , void *buf , unsigned int nbyte ) ;
extern int ptrace(int request , void *pid , void *addr , int data ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
extern unsigned int strnlen(char const   *s , unsigned int maxlen ) ;
struct _2_main_1_opaque_NodeStruct *_2_main_1_opaque_ptr_2  =    (struct _2_main_1_opaque_NodeStruct *)0;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern long clock(void) ;
extern void qsort(void *base , unsigned int nel , unsigned int width , int (*compar)(void *a ,
                                                                                     void *b ) ) ;
extern long time(long *tloc ) ;
extern int rand() ;
extern int read(int filedes , void *buf , unsigned int nbyte ) ;
extern int strcmp(char const   *a , char const   *b ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern double sqrt(double x ) ;
extern int snprintf(char *str , unsigned int size , char const   *format  , ...) ;
extern void *malloc(unsigned int size ) ;
extern  __attribute__((__nothrow__)) long ( __attribute__((__nonnull__(1), __leaf__)) strtol)(char const   * __restrict  __nptr ,
                                                                                              char ** __restrict  __endptr ,
                                                                                              int __base ) ;
struct _2_main_1_opaque_NodeStruct *_2_main_1_opaque_list_2  =    (struct _2_main_1_opaque_NodeStruct *)0;
extern int nanosleep(int *rqtp , int *rmtp ) ;
extern int pthread_mutex_unlock(int *mutex ) ;
extern int pthread_create(void *thread , void *attr , void *start_routine , void *arg ) ;
extern int atoi(char const   *s ) ;
extern int fseek(struct _IO_FILE *stream , long offs , int whence ) ;
extern int fscanf(struct _IO_FILE *stream , char const   *format  , ...) ;
void megaInit(void) ;
int main(int argc , char **argv , char **_formal_envp ) 
{ 
  int a[10] ;
  int i ;
  int m ;
  int c ;
  int l ;
  int u ;
  int mid ;
  long tmp ;
  long tmp___0 ;
  struct _2_main_1_opaque_NodeStruct *p14 ;
  int r15 ;
  struct _2_main_1_opaque_NodeStruct *p16 ;
  int r17 ;
  struct _2_main_1_opaque_NodeStruct *p18 ;

  {
  megaInit();
  _global_argc = argc;
  _global_argv = argv;
  _global_envp = _formal_envp;

  {  /* __blockattribute__(__ATOMIC__)*/ 
  p14 = (struct _2_main_1_opaque_NodeStruct *)malloc(sizeof(struct _2_main_1_opaque_NodeStruct ));
  p14->next = p14;
  p14->prev = p14;
  _2_main_1_opaque_list_1 = p14;
  r17 = rand();
  p18 = (struct _2_main_1_opaque_NodeStruct *)malloc(sizeof(struct _2_main_1_opaque_NodeStruct ));
  p18->data = 0 * r17;
  p18->next = _2_main_1_opaque_list_1->next;
  p18->prev = _2_main_1_opaque_list_1;
  (_2_main_1_opaque_list_1->next)->prev = p18;
  _2_main_1_opaque_list_1->next = p18;
  r15 = rand();
  p16 = (struct _2_main_1_opaque_NodeStruct *)malloc(sizeof(struct _2_main_1_opaque_NodeStruct ));
  p16->data = 1 * r15;
  p16->next = _2_main_1_opaque_list_1->next;
  p16->prev = _2_main_1_opaque_list_1;
  (_2_main_1_opaque_list_1->next)->prev = p16;
  _2_main_1_opaque_list_1->next = p16;
  _2_main_1_opaque_ptr_1 = _2_main_1_opaque_list_1->next;
  _2_main_1_opaque_ptr_2 = _2_main_1_opaque_ptr_1;
  _2_main_1_opaque_ptr_2 = _2_main_1_opaque_ptr_2->next;
  }


  if (((unsigned int )((((12 - argc) & - (12 >= argc)) >> 31) - (((12 - argc) & - (12 >= argc)) ^ (((12 - argc) & - (12 >= argc)) >> 31))) >> 31U) & 1) {
    return (1);
  }
  c = 0;
  i = 1;
  if (_2_main_1_opaque_ptr_1 == _2_main_1_opaque_ptr_2) {

  } else {
    while (1) {
      if (! (((unsigned int )((i - ((argc + ~ 1) + 1)) ^ ((i ^ ((argc + ~ 1) + 1)) & ((i - ((argc + ~ 1) + 1)) ^ i))) >> 31U) & 1)) {
        if (_2_main_1_opaque_ptr_1 != _2_main_1_opaque_ptr_2) {
          break;
        } else
        if (_2_main_1_opaque_ptr_1 != _2_main_1_opaque_ptr_2) {
          __asm__  volatile   (".byte 0xc7,0x85,0xa8":);
        } else {

        }
      }
      tmp = strtol((char const   */* __restrict  */)*(argv + i), (char **/* __restrict  */)((void *)0),
                   10);
      a[i - 1] = (int )tmp;
      i = ((i | 1) + (i | 1)) - (i ^ 1);
    }
  }
  if (_2_main_1_opaque_ptr_1 == _2_main_1_opaque_ptr_2) {
    c = main(l, argv, _formal_envp);
  } else {

  }
  tmp___0 = strtol((char const   */* __restrict  */)*(argv + ((argc + ~ 1) + 1)),
                   (char **/* __restrict  */)((void *)0), 0);
  m = (int )tmp___0;
  l = 0;
  u = (argc + ~ 2) + 1;
  if (_2_main_1_opaque_ptr_1 != _2_main_1_opaque_ptr_2) {
    if (_2_main_1_opaque_ptr_1 == _2_main_1_opaque_ptr_2) {
      u = main(m, argv, _formal_envp);
    } else {

    }
    while (1) {
      if (! (((unsigned int )((~ (l ^ u) >> 1) + (l & ~ u)) >> 31U) & 1)) {
        if (_2_main_1_opaque_ptr_1 == _2_main_1_opaque_ptr_2) {
          return (r15);
        } else {
          break;
        }
      }
      mid = (l | ((u & ~ l) - (~ u & l)) / 2) + (l & ((u & ~ l) - (~ u & l)) / 2);
      if (_2_main_1_opaque_ptr_1 == _2_main_1_opaque_ptr_2) {
        if ((((unsigned int )(~ ((m - a[mid]) | (a[mid] - m))) >> 31U) & 1) == u) {
          if ((((unsigned int )((m - a[mid]) ^ ((m ^ a[mid]) & ((m - a[mid]) ^ m))) >> 31U) & 1) > l) {
            if ((_2_main_1_opaque_ptr_1 != _2_main_1_opaque_ptr_2) == u) {

            } else
            if ((_2_main_1_opaque_ptr_1 != _2_main_1_opaque_ptr_2) < r15) {
              c = main(r15, _formal_envp + -1, _formal_envp + 1);
            } else {

            }
            l = u;
          } else {
            u = c;
          }
        } else {
          c = mid;
          while ((_2_main_1_opaque_ptr_1 == _2_main_1_opaque_ptr_2) != u) {
            while ((_2_main_1_opaque_ptr_1 != _2_main_1_opaque_ptr_2) < m) {
              if ((_2_main_1_opaque_ptr_1 == _2_main_1_opaque_ptr_2) >= r15) {
                __asm__  volatile   (".byte 0xff,0xff,0xeb,0x11":);
              } else {
                __asm__  volatile   (".byte 0xff,0xff,0xeb,0x11":);
              }
            }
          }
        }
      } else
      if (((unsigned int )(~ ((m - a[mid]) | (a[mid] - m))) >> 31U) & 1) {
        c = 1;
        if (_2_main_1_opaque_ptr_1 == _2_main_1_opaque_ptr_2) {
          if (_2_main_1_opaque_ptr_1 != _2_main_1_opaque_ptr_2) {
            if (_2_main_1_opaque_ptr_1 == _2_main_1_opaque_ptr_2) {
              __asm__  volatile   (".byte 0xff,0xff,0xeb,0x11":);
            } else {
              __asm__  volatile   (".byte 0xff,0xff,0xeb,0x11":);
            }
          } else {
            while ((_2_main_1_opaque_ptr_1 == _2_main_1_opaque_ptr_2) >= l) {
              __asm__  volatile   (".byte 0xff,0xff,0xeb,0x11":);
            }
          }
        } else
        if (_2_main_1_opaque_ptr_1 == _2_main_1_opaque_ptr_2) {
          return (u);
        } else {
          break;
        }
      } else
      if (((unsigned int )((m - a[mid]) ^ ((m ^ a[mid]) & ((m - a[mid]) ^ m))) >> 31U) & 1) {
        u = ((mid & ~ 1) + (mid & ~ 1)) - (mid ^ 1);
      } else {
        if (_2_main_1_opaque_ptr_1 != _2_main_1_opaque_ptr_2) {
          {
          if (_2_main_1_opaque_ptr_1 != _2_main_1_opaque_ptr_2) {

          } else {
            mid = main(i, argv, _formal_envp);
          }
          if (_2_main_1_opaque_ptr_1 != _2_main_1_opaque_ptr_2) {

          } else {
            c = main(i, _formal_envp, _formal_envp);
          }
          }
        } else {

        }
        l = ((mid | 1) + (mid | 1)) - (mid ^ 1);
      }
    }
  } else {

  }
  if (_2_main_1_opaque_ptr_1 == _2_main_1_opaque_ptr_2) {
    __asm__  volatile   (".byte 0x36,0x41":);
  } else
  if (((unsigned int )(~ (c | - c)) >> 31U) & 1) {
    printf((char const   */* __restrict  */)"The number is not found.\n");
  } else {
    printf((char const   */* __restrict  */)"The number is found.\n");
  }
  return (0);
}
}
void megaInit(void) 
{ 


  {

}
}
