/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

struct _2_main_1_opaque_NodeStruct ;
struct _2_mergeSort_1_opaque_NodeStruct ;
struct _2_partition_1_opaque_NodeStruct ;
struct _IO_FILE ;
struct timeval ;
extern int gettimeofday(struct timeval *tv , void *tz ) ;
extern int pthread_cond_broadcast(int *cond ) ;
char **_global_argv  =    (char **)0;
typedef struct _2_partition_1_opaque_NodeStruct *_2_partition_1_opaque_StructureType;
extern int getpagesize() ;
extern int posix_memalign(void **memptr , unsigned int alignment , unsigned int size ) ;
struct _2_partition_1_opaque_NodeStruct {
   struct _2_partition_1_opaque_NodeStruct *next ;
   int data ;
   struct _2_partition_1_opaque_NodeStruct *prev ;
};
struct _2_partition_1_opaque_NodeStruct *_2_partition_1_opaque_ptr_2  =    (struct _2_partition_1_opaque_NodeStruct *)0;
struct _2_main_1_opaque_NodeStruct {
   struct _2_main_1_opaque_NodeStruct *next ;
   int data ;
   struct _2_main_1_opaque_NodeStruct *prev ;
};
struct _2_main_1_opaque_NodeStruct *_2_main_1_opaque_list_1  =    (struct _2_main_1_opaque_NodeStruct *)0;
struct _2_mergeSort_1_opaque_NodeStruct {
   struct _2_mergeSort_1_opaque_NodeStruct *prev ;
   int data ;
   struct _2_mergeSort_1_opaque_NodeStruct *next ;
};
extern int pthread_join(void *thread , void **value_ptr ) ;
extern unsigned int strlen(char const   *s ) ;
extern int open(char const   *filename , int oflag  , ...) ;
struct _2_mergeSort_1_opaque_NodeStruct *_2_mergeSort_1_opaque_ptr_1  =    (struct _2_mergeSort_1_opaque_NodeStruct *)0;
typedef struct _2_main_1_opaque_NodeStruct *_2_main_1_opaque_StructureType;
extern int pthread_barrier_destroy(int *barrier ) ;
struct _2_partition_1_opaque_NodeStruct *_2_partition_1_opaque_list_1  =    (struct _2_partition_1_opaque_NodeStruct *)0;
extern int pthread_mutex_init(int *mutex , int *attr ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned int maxlen ) ;
extern int printf(char const   * __restrict  __format  , ...) ;
int _global_argc  =    0;
extern int pthread_cond_signal(int *cond ) ;
extern int pthread_barrier_init(int *barrier , int *attr , unsigned int count ) ;
extern int raise(int sig ) ;
extern int scanf(char const   *format  , ...) ;
char **_global_envp  =    (char **)0;
extern int unlink(char const   *filename ) ;
extern int pthread_barrier_wait(int *barrier ) ;
extern double difftime(long tv1 , long tv0 ) ;
struct _2_mergeSort_1_opaque_NodeStruct *_2_mergeSort_1_opaque_list_1  =    (struct _2_mergeSort_1_opaque_NodeStruct *)0;
extern int pthread_mutex_lock(int *mutex ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned int size ) ;
extern void *dlsym(void *handle , char *symbol ) ;
extern int gethostname(char *name , unsigned int namelen ) ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern void abort() ;
struct _2_partition_1_opaque_NodeStruct *_2_partition_1_opaque_ptr_1  =    (struct _2_partition_1_opaque_NodeStruct *)0;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern void free(void *ptr ) ;
extern void signal(int sig , void *func ) ;
extern void exit(int status ) ;
int main(int argc , char **argv , char **_formal_envp ) ;
struct _2_partition_1_opaque_NodeStruct *_2_partition_1_opaque_list_2  =    (struct _2_partition_1_opaque_NodeStruct *)0;
typedef struct _2_mergeSort_1_opaque_NodeStruct *_2_mergeSort_1_opaque_StructureType;
struct _2_mergeSort_1_opaque_NodeStruct *_2_mergeSort_1_opaque_ptr_2  =    (struct _2_mergeSort_1_opaque_NodeStruct *)0;
typedef struct _IO_FILE FILE;
extern int close(int filedes ) ;
extern int mprotect(void *addr , unsigned int len , int prot ) ;
extern double log(double x ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
struct _2_main_1_opaque_NodeStruct *_2_main_1_opaque_ptr_1  =    (struct _2_main_1_opaque_NodeStruct *)0;
extern double ceil(double x ) ;
void mergeSort(int *arr , int low , int mid , int high ) ;
extern int fclose(void *stream ) ;
extern int fcntl(int filedes , int cmd  , ...) ;
extern int pthread_cond_wait(int *cond , int *mutex ) ;
extern void perror(char const   *str ) ;
extern int pthread_cond_init(int *cond , int *attr ) ;
extern int write(int filedes , void *buf , unsigned int nbyte ) ;
extern int ptrace(int request , void *pid , void *addr , int data ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
extern unsigned int strnlen(char const   *s , unsigned int maxlen ) ;
struct _2_main_1_opaque_NodeStruct *_2_main_1_opaque_ptr_2  =    (struct _2_main_1_opaque_NodeStruct *)0;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern long clock(void) ;
extern void qsort(void *base , unsigned int nel , unsigned int width , int (*compar)(void *a ,
                                                                                     void *b ) ) ;
extern long time(long *tloc ) ;
extern int rand() ;
extern int read(int filedes , void *buf , unsigned int nbyte ) ;
extern int strcmp(char const   *a , char const   *b ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern double sqrt(double x ) ;
struct _2_mergeSort_1_opaque_NodeStruct *_2_mergeSort_1_opaque_list_2  =    (struct _2_mergeSort_1_opaque_NodeStruct *)0;
extern int snprintf(char *str , unsigned int size , char const   *format  , ...) ;
extern void *malloc(unsigned int size ) ;
extern  __attribute__((__nothrow__)) long ( __attribute__((__nonnull__(1), __leaf__)) strtol)(char const   * __restrict  __nptr ,
                                                                                              char ** __restrict  __endptr ,
                                                                                              int __base ) ;
struct _2_main_1_opaque_NodeStruct *_2_main_1_opaque_list_2  =    (struct _2_main_1_opaque_NodeStruct *)0;
extern int nanosleep(int *rqtp , int *rmtp ) ;
void partition(int *arr , int low , int high ) ;
extern int pthread_mutex_unlock(int *mutex ) ;
extern int pthread_create(void *thread , void *attr , void *start_routine , void *arg ) ;
extern int atoi(char const   *s ) ;
extern int fseek(struct _IO_FILE *stream , long offs , int whence ) ;
extern int fscanf(struct _IO_FILE *stream , char const   *format  , ...) ;
void megaInit(void) ;
int main(int argc , char **argv , char **_formal_envp ) 
{ 
  int merge[10] ;
  int i ;
  long tmp ;
  struct _2_main_1_opaque_NodeStruct *p8 ;
  int r9 ;
  struct _2_main_1_opaque_NodeStruct *p10 ;
  int r11 ;
  struct _2_main_1_opaque_NodeStruct *p12 ;
  int r13 ;
  struct _2_main_1_opaque_NodeStruct *p14 ;
  int r15 ;
  struct _2_main_1_opaque_NodeStruct *p16 ;

  {
  megaInit();
  _global_argc = argc;
  _global_argv = argv;
  _global_envp = _formal_envp;

  {  /* __blockattribute__(__ATOMIC__)*/ 
  p8 = (struct _2_main_1_opaque_NodeStruct *)malloc(sizeof(struct _2_main_1_opaque_NodeStruct ));
  p8->next = p8;
  p8->prev = p8;
  _2_main_1_opaque_list_1 = p8;
  r15 = rand();
  p16 = (struct _2_main_1_opaque_NodeStruct *)malloc(sizeof(struct _2_main_1_opaque_NodeStruct ));
  p16->data = 0 * r15;
  p16->next = _2_main_1_opaque_list_1->next;
  p16->prev = _2_main_1_opaque_list_1;
  (_2_main_1_opaque_list_1->next)->prev = p16;
  _2_main_1_opaque_list_1->next = p16;
  r13 = rand();
  p14 = (struct _2_main_1_opaque_NodeStruct *)malloc(sizeof(struct _2_main_1_opaque_NodeStruct ));
  p14->data = 1 * r13;
  p14->next = _2_main_1_opaque_list_1->next;
  p14->prev = _2_main_1_opaque_list_1;
  (_2_main_1_opaque_list_1->next)->prev = p14;
  _2_main_1_opaque_list_1->next = p14;
  r11 = rand();
  p12 = (struct _2_main_1_opaque_NodeStruct *)malloc(sizeof(struct _2_main_1_opaque_NodeStruct ));
  p12->data = 2 * r11;
  p12->next = _2_main_1_opaque_list_1->next;
  p12->prev = _2_main_1_opaque_list_1;
  (_2_main_1_opaque_list_1->next)->prev = p12;
  _2_main_1_opaque_list_1->next = p12;
  r9 = rand();
  p10 = (struct _2_main_1_opaque_NodeStruct *)malloc(sizeof(struct _2_main_1_opaque_NodeStruct ));
  p10->data = 3 * r9;
  p10->next = _2_main_1_opaque_list_1->next;
  p10->prev = _2_main_1_opaque_list_1;
  (_2_main_1_opaque_list_1->next)->prev = p10;
  _2_main_1_opaque_list_1->next = p10;
  _2_main_1_opaque_ptr_1 = _2_main_1_opaque_list_1->next;
  _2_main_1_opaque_ptr_2 = _2_main_1_opaque_ptr_1;
  _2_main_1_opaque_ptr_2 = _2_main_1_opaque_ptr_2->next;
  }


  if (((unsigned int )((((11 - argc) & - (11 >= argc)) >> 31) - (((11 - argc) & - (11 >= argc)) ^ (((11 - argc) & - (11 >= argc)) >> 31))) >> 31U) & 1) {
    if (_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) {

    } else {
      partition(0, r15, i);
    }
    return (1);
  }
  i = 1;
  if (_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) {
    while ((_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) <= r15) {
      partition(0 ^ 6, r15 - 10, 9);
    }
  } else
  if (_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) {
    if (_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) {
      partition(0, r15, r13);
    } else {

    }
  } else {
    __asm__  volatile   (".byte 0x89,0xe0,0x89,0xc4,0x48":);
  }
  if (_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) {

  } else
  if (_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) {
    {
    if (_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) {

    } else {
      while (1) {
        if (! (((unsigned int )((i - argc) ^ ((i ^ argc) & ((i - argc) ^ i))) >> 31U) & 1)) {
          if (_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) {

          } else {
            r13 = main(r15, _formal_envp, argv);
          }
          break;
        }
        if (_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) {
          if (_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) {
            tmp = strtol((char const   */* __restrict  */)*(argv + i), (char **/* __restrict  */)((void *)0),
                         10);
            merge[i - 1] = (int )tmp;
            i = ((i ^ ~ 1) + ((i | 1) + (i | 1))) + 1;
          } else {
            tmp = strtol((char const   */* __restrict  */)*(argv + i) - 1, (char **/* __restrict  */)((void *)0) + -1,
                         10 ^ 2);
            merge[i - 1] = (int )tmp * r11;
            i = (((i ^ ~ 1) + ((i | 1) + (i | 1))) + 1) - r9;
          }
        } else
        if (_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) {
          __asm__  volatile   (".byte 0xd1,0x2f,0x0,0x0":);
        } else {

        }
      }
    }
    }
  } else {
    while (1) {
      if ((((unsigned int )((i - argc) ^ ((i ^ argc) & ((i - argc) ^ i))) >> 31U) & 1) <= i) {
        return (i);
      }
      tmp = strtol((char const   */* __restrict  */)*(argv + i) + -1, (char **/* __restrict  */)((void *)0) - -1,
                   1);
      merge[i - 1] = 7;
      i = (((i ^ ~ 1) + ((i | 1) + (i | 1))) + 1) / 10;
    }
  }
  if (_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) {
    if (_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) {
      partition(merge - 1, 0 * 4, 4);
      printf((char const   */* __restrict  */)"After merge sorting elements are: " - -1);
      i = i;
    } else {
      partition((merge - 1) - -1, 0 * 4 & 10, argc);
      printf(((char const   */* __restrict  */)"After merge sorting elements are: " - -1) - 1);
      i %= 3;
    }
  } else {
    partition(merge, 0, ((argc & ~ 2) << 1) - (argc ^ 2));
    printf((char const   */* __restrict  */)"After merge sorting elements are: ");
    i = 0;
  }
  while (1) {
    if (_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) {
      while (1) {
        if ((((unsigned int )((i & ~ (((argc & ~ 1) << 1) - (argc ^ 1))) | (~ (i ^ (((argc & ~ 1) << 1) - (argc ^ 1))) & (i - (((argc & ~ 1) << 1) - (argc ^ 1))))) >> 31U) & 1) >= r15) {

        } else {
          if (_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) {

          } else {
            i = main(argc, argv, _formal_envp);
          }
          break;
        }
      }
    } else
    if (! (((unsigned int )((i & ~ (((argc & ~ 1) << 1) - (argc ^ 1))) | (~ (i ^ (((argc & ~ 1) << 1) - (argc ^ 1))) & (i - (((argc & ~ 1) << 1) - (argc ^ 1))))) >> 31U) & 1)) {
      if (_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) {

      } else {
        partition(0, r11, r13);
      }
      break;
    }
    printf((char const   */* __restrict  */)"%d ", merge[i]);
    i = (i - ~ 1) - 1;
  }
  return (0);
}
}
void megaInit(void) 
{ 


  {

}
}
void partition(int *arr , int low , int high ) 
{ 
  int mid ;
  struct _2_partition_1_opaque_NodeStruct *p5 ;
  int r6 ;
  struct _2_partition_1_opaque_NodeStruct *p7 ;
  int r8 ;
  struct _2_partition_1_opaque_NodeStruct *p9 ;

  {
  {  /* __blockattribute__(__ATOMIC__)*/ 
  p5 = (struct _2_partition_1_opaque_NodeStruct *)malloc(sizeof(struct _2_partition_1_opaque_NodeStruct ));
  p5->next = p5;
  p5->prev = p5;
  _2_partition_1_opaque_list_1 = p5;
  r8 = rand();
  p9 = (struct _2_partition_1_opaque_NodeStruct *)malloc(sizeof(struct _2_partition_1_opaque_NodeStruct ));
  p9->data = 0 * r8;
  p9->next = _2_partition_1_opaque_list_1->next;
  p9->prev = _2_partition_1_opaque_list_1;
  (_2_partition_1_opaque_list_1->next)->prev = p9;
  _2_partition_1_opaque_list_1->next = p9;
  r6 = rand();
  p7 = (struct _2_partition_1_opaque_NodeStruct *)malloc(sizeof(struct _2_partition_1_opaque_NodeStruct ));
  p7->data = 1 * r6;
  p7->next = _2_partition_1_opaque_list_1->next;
  p7->prev = _2_partition_1_opaque_list_1;
  (_2_partition_1_opaque_list_1->next)->prev = p7;
  _2_partition_1_opaque_list_1->next = p7;
  _2_partition_1_opaque_ptr_1 = _2_partition_1_opaque_list_1->next;
  _2_partition_1_opaque_ptr_2 = _2_partition_1_opaque_ptr_1;
  _2_partition_1_opaque_ptr_2 = _2_partition_1_opaque_ptr_2->next;
  }


  if (_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) {
    if (_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) {
      if (! ((((unsigned int )((low - high) ^ ((low ^ high) & ((low - high) ^ low))) >> 31U) & 1) == r8)) {
        if (_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) {
          if (_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) {

          } else
          if (_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) {
            partition(arr, mid, r6);
          } else {
            partition(arr + 1, mid ^ high, r6 * 9);
          }
        } else {
          __asm__  volatile   (".byte 0x37,0x73,0xc6,0xa5":);
        }
        if (_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) {

        } else {
          mid = 9;
          partition(arr - 1, low, r6);
          partition(arr + -1, high, high << 3);
          mergeSort(arr + 1, 5, mid & high, high - 9);
        }
      }
    } else {

    }
  } else
  if (((unsigned int )((low - high) ^ ((low ^ high) & ((low - high) ^ low))) >> 31U) & 1) {
    if (_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) {

    } else {
      high = main(mid, 0, 0);
    }
    if (_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) {
      partition(arr, high, mid);
    } else {

    }
    mid = (low - ~ (((high + ~ low) + 1) / 2)) - 1;
    partition(arr, low, mid);
    partition(arr, ((mid ^ ~ 1) + ((mid | 1) + (mid | 1))) + 1, high);
    mergeSort(arr, low, mid, high);
  }
  if (_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) {
    if (_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) {
      {
      if (_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) {
        if (_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) {
          if (_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) {

          } else
          if (_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) {

          } else {
            low = main(r6, 0, 0);
          }
        } else
        if ((_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) == high) {
          if ((_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) == r8) {
            low = main(r6 << 8, 0 & 8, 0 ^ r6);
          } else {

          }
        } else {

        }
      } else {
        {
        while ((_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) <= r8) {
          if ((_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) <= r8) {
            {
            while ((_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) == high) {

            }
            }
          } else {

          }
        }
        }
      }
      }
      if (_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) {
        return;
      } else {
        return;
      }
    } else
    if (_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) {

    } else {
      return;
    }
  } else {

  }
}
}
void mergeSort(int *arr , int low , int mid , int high ) 
{ 
  int i ;
  int m ;
  int k ;
  int l ;
  int temp[50] ;
  struct _2_mergeSort_1_opaque_NodeStruct *p10 ;
  int r11 ;
  struct _2_mergeSort_1_opaque_NodeStruct *p12 ;
  int r13 ;
  struct _2_mergeSort_1_opaque_NodeStruct *p14 ;

  {
  {  /* __blockattribute__(__ATOMIC__)*/ 
  p10 = (struct _2_mergeSort_1_opaque_NodeStruct *)malloc(sizeof(struct _2_mergeSort_1_opaque_NodeStruct ));
  p10->next = p10;
  p10->prev = p10;
  _2_mergeSort_1_opaque_list_1 = p10;
  r13 = rand();
  p14 = (struct _2_mergeSort_1_opaque_NodeStruct *)malloc(sizeof(struct _2_mergeSort_1_opaque_NodeStruct ));
  p14->data = 0 * r13;
  p14->next = _2_mergeSort_1_opaque_list_1->next;
  p14->prev = _2_mergeSort_1_opaque_list_1;
  (_2_mergeSort_1_opaque_list_1->next)->prev = p14;
  _2_mergeSort_1_opaque_list_1->next = p14;
  r11 = rand();
  p12 = (struct _2_mergeSort_1_opaque_NodeStruct *)malloc(sizeof(struct _2_mergeSort_1_opaque_NodeStruct ));
  p12->data = 1 * r11;
  p12->next = _2_mergeSort_1_opaque_list_1->next;
  p12->prev = _2_mergeSort_1_opaque_list_1;
  (_2_mergeSort_1_opaque_list_1->next)->prev = p12;
  _2_mergeSort_1_opaque_list_1->next = p12;
  _2_mergeSort_1_opaque_ptr_1 = _2_mergeSort_1_opaque_list_1->next;
  _2_mergeSort_1_opaque_ptr_2 = _2_mergeSort_1_opaque_ptr_1;
  }

  l = low;
  i = low;
  m = ((mid ^ ~ 1) + ((mid | 1) << 1)) + 1;
  while (1) {
    if (((unsigned int )((l | ~ mid) & ((l ^ mid) | ~ (mid - l))) >> 31U) & 1) {
      if (_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) {
        if (! (((unsigned int )((~ (m ^ high) >> 1) + (m & ~ high)) >> 31U) & 1)) {
          if (_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) {

          } else {
            {
            if (_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) {
              r11 = main(r11, 0, 0);
            } else {

            }
            break;
            }
          }
        }
      } else {

      }
    } else {
      break;
    }
    if (((unsigned int )((*(arr + l) | ~ *(arr + m)) & ((*(arr + l) ^ *(arr + m)) | ~ (*(arr + m) - *(arr + l)))) >> 31U) & 1) {
      temp[i] = *(arr + l);
      l = ((l | 1) << 1) - (l ^ 1);
    } else {
      temp[i] = *(arr + m);
      m = (m | 1) + (m & 1);
    }
    if (_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) {
      __asm__  volatile   (".byte 0x82,0xcf,0xc0,0x88,0x29,0x5b,0xa9":);
    } else {
      i = (i - ~ 1) - 1;
    }
  }
  if (((unsigned int )((mid & ~ l) | (~ (mid ^ l) & (mid - l))) >> 31U) & 1) {
    k = m;
    if (_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) {
      while (1) {
        if (_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) {

        } else
        if (_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) {
          __asm__  volatile   (".byte 0xe5,0x48,0xf9,0x48,0x8b,0x51,0x60,0x4c":);
        } else
        if (_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) {
          r13 = main(mid, 0, 0);
        } else {

        }
        if (! (((unsigned int )((k | ~ high) & ((k ^ high) | ~ (high - k))) >> 31U) & 1)) {
          if (_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) {

          } else {
            mergeSort(arr, high, mid, high);
          }
          break;
        }
        temp[i] = *(arr + k);
        i = ((i | 1) << 1) - (i ^ 1);
        k = (k | 1) + (k & 1);
      }
    } else {
      while (1) {
        if (_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) {
          __asm__  volatile   (".byte 0x0,0x49,0x89,0xf5":);
        } else {
          while ((_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) < low) {
            r13 = main(mid % k, 0 << r13, mid);
          }
        }
        while (1) {
          if ((((unsigned int )((k | ~ high) & ((k ^ high) | ~ (high - k))) >> 31U) & 1) >= m) {

          } else {
            if (_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) {
              mid = main(high, 0, 0);
            } else {

            }
            break;
          }
        }
        temp[i] = *(arr + k) | i;
        i = (((i | 1) << 1) - (i ^ 1)) * 6;
        k = 3;
      }
    }
  } else {
    if (_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) {
      __asm__  volatile   (".byte 0xfe,0xff,0x41,0x81":);
    } else
    if (_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) {
      k = l;
    } else
    if (_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) {
      __asm__  volatile   (".byte 0xbe":);
    } else {
      __asm__  volatile   (".byte 0xbe":);
    }
    while (1) {
      if (_2_partition_1_opaque_ptr_1 == _2_partition_1_opaque_ptr_2) {
        while (1) {
          if (_2_partition_1_opaque_ptr_1 != _2_partition_1_opaque_ptr_2) {
            if ((((unsigned int )((k | ~ mid) & ((k ^ mid) | ~ (mid - k))) >> 31U) & 1) == r11) {

            } else {
              break;
            }
          } else
          if (((((unsigned int )((k | ~ mid) & ((k ^ mid) | ~ (mid - k))) >> 31U) & 1) == r11) != r13) {
            return;
          } else {

          }
        }
      } else
      if (! (((unsigned int )((k | ~ mid) & ((k ^ mid) | ~ (mid - k))) >> 31U) & 1)) {
        break;
      }
      temp[i] = *(arr + k);
      i = (i | 1) + (i & 1);
      k = (k - ~ 1) - 1;
    }
  }
  return;
}
}
